# Site settings
title: "Conway's Game of Life"
description: "Conway's Game of Life is a cellular automaton developed by John Horton Conway in 1970."
url: "http://stefandollase.github.io" # the base hostname & protocol for your site
baseurl: "/game-of-life-js" # the subpath of your site, e.g. /blog/

# About the author
author_fullname: "Stefan Dollase"
email: "game-of-life-js@stefandollase.de"
github_username: "stefandollase"

# Disqus settings
#disqus_shortname: ""
#disqus_identifier_prefix: ""

# Build settings
markdown: kramdown
